"""another

Revision ID: 6e335abaf0b6
Revises: 042636a1107b
Create Date: 2023-01-12 12:51:51.304464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e335abaf0b6'
down_revision = '042636a1107b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appjobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=True),
    sa.Column('job_status', sa.Enum('Unknown', 'Pending', 'Running', 'Completed', name='jobstatus'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appjobs')
    # ### end Alembic commands ###
